linters:
  enable:
    - govet
    - golint
    - errcheck
    - staticcheck
    - gosimple
    - deadcode
run:
  timeout: 5m
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - golint